// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import AdminController from "./admin_controller"
application.register("admin", AdminController)

import ALikeController from "./alike_controller"
application.register("alike", ALikeController)

import FeedController from "./feed_controller"
application.register("feed", FeedController)

import SearchController from "./search_controller"
application.register("search", SearchController)
